import { Geist, Geist_Mono } from "next/font/google";
// import { Montserrat, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const montserrat = Montserrat({
//     variable: "--font-montserrat",
//     subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RiverGuard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {/*<body className={`${montserrat.variable} ${geistMono.variable}`}>*/}
        {children}
      </body>
    </html>
  );
}
